<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>A4U3.Repository</AssemblyName>
    <PackageId>A4U3.Repository</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\A4U3.Domain\A4U3.Domain.csproj" />
    <ProjectReference Include="..\A4U3.EFContext\A4U3.EFContext.csproj" />
  </ItemGroup>

</Project>
